# Site settings
author: Kayla Kingston
title: Kayla Codes
header-img: img/home-bg.png
email: kkingston09@gmail.com
copyright_name: Kayla Kingston
description: > # this means to ignore newlines until "baseurl:"
  The trials and errors of learning to speak computer.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kkingston

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
